apiVersion: liberty.websphere.ibm.com/v1
kind: WebSphereLibertyApplication
metadata:
  name: daytrader7
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  license:
    accept: true
    edition: IBM WebSphere Application Server
    productEntitlementSource: Standalone
  applicationVersion: '1.0'
  applicationImage: 'default-route-openshift-image-registry.apps.cp4bamig1i.cp.fyre.ibm.com/bb/sample-daytrader7:latest'
  route:
    insecureEdgeTerminationPolicy: None
    termination: edge
    path: /daytrader
  expose: true
  manageTLS: true
  replicas: 1
  service:
    portName: liveness-port
    port: 9082
    type: ClusterIP
  probes:
    startup:
      httpGet:
        path: /health
        port: liveness-port
      failureThreshold: 10
      periodSeconds: 10
    liveness:
      httpGet:
        path: /health
        port: liveness-port
      failureThreshold: 5
      periodSeconds: 10
    readiness:
      httpGet:
        path: /daytrader
        port: liveness-port
      failureThreshold: 5
      periodSeconds: 10
  env:
    - name: tradeDbHost
      value: trade-db2
    - name: tradeDbPort
      value: "50000"
    - name: tradeDbName
      value: TRADEDB
    - name: dbUser
      value: db2inst1
    - name: dbPass
      valueFrom:
        secretKeyRef:
          name: db-credential
          key: dbpw
  pullPolicy: Always
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 500m
      memory: 2Gi
